# noqa: INP001
r"""A maintenance script to (re)generate the ``feu.compat.discovered``
modules.

For each package name given, this fetches the current PyPI metadata via
``discover_compat_targets`` and writes the result as a Python module
under ``src/feu/compat/discovered/``, to be committed to the repository.
Re-run this script periodically to refresh the automatically discovered
compatibility data.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from feu.compat import discover_compat_targets
from feu.compat.packages import get_package_names

logger: logging.Logger = logging.getLogger(__name__)

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "src" / "feu" / "compat" / "discovered"

MODULE_TEMPLATE = '''\
r"""Automatically discovered compatibility constraints for
``{pkg_name}``.

Generated by ``debug/generate_discovered_compat.py``. Do not edit by
hand: re-run the script to refresh this module.
"""

from __future__ import annotations

__all__ = ["PKG_NAME", "compat"]

from feu.compat.registry import VersionRange
from feu.compat.target import Target

PKG_NAME = {pkg_name!r}


def compat() -> dict[Target, list[VersionRange]]:
    r"""Return the precomputed compatibility constraints for
    ``{pkg_name}``."""
    return {compat!r}
'''


def module_name(pkg_name: str) -> str:
    r"""Convert a PyPI package name to a valid Python module name."""
    return re.sub(r"[^0-9a-zA-Z_]", "_", pkg_name).lower()


def generate(pkg_name: str) -> None:
    r"""Discover and write the compatibility module for one package."""
    logger.info("Discovering compatibility targets for %s...", pkg_name)
    compat = discover_compat_targets(pkg_name)
    content = MODULE_TEMPLATE.format(pkg_name=pkg_name, compat=compat)
    path = OUTPUT_DIR / f"{module_name(pkg_name)}.py"
    path.write_text(content)
    logger.info("Wrote %s", path)


def main() -> None:
    r"""Define the main function."""
    for pkg_name in get_package_names():
        generate(pkg_name)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
