r"""Contain the user-defined package/target compatibility overrides.

Each submodule of this package holds hand-curated overrides for one
package, initially seeded from ``feu.compat.defaults.DEFAULT_COMPAT``.
This is the user-defined counterpart to ``feu.compat.discovered``: it
plays the same role for the registry's ``override`` layer that
``feu.compat.discovered`` plays for the ``base`` layer, except its
content is meant to be edited by hand rather than regenerated by a
discovery script.
"""

from __future__ import annotations

__all__ = ["register_overrides"]

import importlib
import pkgutil
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from feu.compat.registry import CompatRegistry


def register_overrides(registry: CompatRegistry) -> None:
    r"""Populate a registry's override layer with the user-defined
    package compatibility constraints.

    Every submodule of ``feu.compat.overrides`` is imported and must
    define ``PKG_NAME`` (the real package name) and a ``compat()``
    function returning a mapping of ``Target`` to a list of
    ``VersionRange`` for that package.

    Args:
        registry: The registry to populate.
    """
    for module_info in pkgutil.iter_modules(__path__):
        module = importlib.import_module(f"{__name__}.{module_info.name}")
        registry.register_many({module.PKG_NAME: module.compat()}, layer="override", exist_ok=True)
