r"""Automatically discovered compatibility constraints for
``numpy``.

Generated by ``dev/generate_discovered_compat.py``. Do not edit by
hand: re-run the script to refresh this module.
"""

from __future__ import annotations

__all__ = ["PKG_NAME", "compat"]

from feu.compat.registry import VersionRange
from feu.compat.target import Target

PKG_NAME = "numpy"


def compat() -> dict[Target, list[VersionRange]]:
    r"""Return the precomputed compatibility constraints for
    ``numpy``."""
    return {
        Target(python_version="3.9", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.19.3", max="2.0.2")
        ],
        Target(python_version="3.9", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.19.3", max="2.0.2")
        ],
        Target(python_version="3.9", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.19.3", max="2.0.2")
        ],
        Target(python_version="3.9", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.21.0", max="2.0.2")
        ],
        Target(python_version="3.9", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.19.3", max="2.0.2")
        ],
        Target(python_version="3.9", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.10", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.21.2", max="2.2.6")
        ],
        Target(python_version="3.10", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.21.2", max="2.2.6")
        ],
        Target(python_version="3.10", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.21.4", max="2.2.6")
        ],
        Target(python_version="3.10", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.21.3", max="2.2.6")
        ],
        Target(python_version="3.10", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.21.3", max="2.2.6")
        ],
        Target(python_version="3.10", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.11", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.23.2", max="2.4.6")
        ],
        Target(python_version="3.11", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.23.2", max="2.4.6")
        ],
        Target(python_version="3.11", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.23.2", max="2.4.6")
        ],
        Target(python_version="3.11", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.23.2", max="2.4.6")
        ],
        Target(python_version="3.11", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.23.2", max="2.4.6")
        ],
        Target(python_version="3.11", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="2.3.0", max="2.4.6")
        ],
        Target(python_version="3.12", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.26.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.26.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.26.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.26.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.26.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="2.3.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="2.1.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="2.1.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="2.1.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="2.1.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="2.1.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="2.3.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=True, os="linux", arch="x86_64"): [
            VersionRange(min="2.1.0", max="2.4.6")
        ],
        Target(python_version="3.13", free_threaded=True, os="linux", arch="arm64"): [
            VersionRange(min="2.1.0", max="2.4.6")
        ],
        Target(python_version="3.13", free_threaded=True, os="macos", arch="x86_64"): [
            VersionRange(min="2.1.0", max="2.4.6")
        ],
        Target(python_version="3.13", free_threaded=True, os="macos", arch="arm64"): [
            VersionRange(min="2.1.0", max="2.4.6")
        ],
        Target(python_version="3.13", free_threaded=True, os="windows", arch="x86_64"): [
            VersionRange(min="2.1.3", max="2.4.6")
        ],
        Target(python_version="3.13", free_threaded=True, os="windows", arch="arm64"): [
            VersionRange(min="2.3.0", max="2.4.6")
        ],
        Target(python_version="3.14", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="linux", arch="x86_64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="linux", arch="arm64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="macos", arch="x86_64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="macos", arch="arm64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="windows", arch="x86_64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="windows", arch="arm64"): [
            VersionRange(min="2.3.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=True, os="linux", arch="x86_64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=True, os="linux", arch="arm64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=True, os="macos", arch="x86_64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=True, os="macos", arch="arm64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=True, os="windows", arch="x86_64"): [
            VersionRange(min="2.5.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=True, os="windows", arch="arm64"): [
            VersionRange(min="2.5.2", max=None)
        ],
    }
