r"""Automatically discovered compatibility constraints for
``polars``.

Generated by ``dev/generate_discovered_compat.py``. Do not edit by
hand: re-run the script to refresh this module.
"""

from __future__ import annotations

__all__ = ["PKG_NAME", "compat"]

from feu.compat.registry import VersionRange
from feu.compat.target import Target

PKG_NAME = "polars"


def compat() -> dict[Target, list[VersionRange]]:
    r"""Return the precomputed compatibility constraints for
    ``polars``."""
    return {
        Target(python_version="3.9", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="0.0.1", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.14.29"),
            VersionRange(min="0.14.31", max="1.36.1"),
        ],
        Target(python_version="3.9", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="0.13.4", max="0.13.18"),
            VersionRange(min="0.13.25", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.13.55"),
            VersionRange(min="0.13.57", max="0.14.10"),
            VersionRange(min="0.14.12", max="0.14.29"),
            VersionRange(min="0.14.31", max="0.17.2"),
            VersionRange(min="0.17.5", max="1.36.1"),
        ],
        Target(python_version="3.9", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max="1.36.1"),
        ],
        Target(python_version="3.9", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="0.12.21", max="0.12.21"),
            VersionRange(min="0.12.23", max="0.13.29"),
            VersionRange(min="0.13.31", max="1.36.1"),
        ],
        Target(python_version="3.9", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.19.3"),
            VersionRange(min="0.19.5", max="1.36.1"),
        ],
        Target(python_version="3.9", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.18.0", max="1.25.0"),
            VersionRange(min="1.25.2", max="1.36.1"),
        ],
        Target(python_version="3.10", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="0.0.1", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.14.29"),
            VersionRange(min="0.14.31", max=None),
        ],
        Target(python_version="3.10", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="0.13.4", max="0.13.18"),
            VersionRange(min="0.13.25", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.13.55"),
            VersionRange(min="0.13.57", max="0.14.10"),
            VersionRange(min="0.14.12", max="0.14.29"),
            VersionRange(min="0.14.31", max="0.17.2"),
            VersionRange(min="0.17.5", max=None),
        ],
        Target(python_version="3.10", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.10", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="0.12.21", max="0.12.21"),
            VersionRange(min="0.12.23", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.10", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.19.3"),
            VersionRange(min="0.19.5", max=None),
        ],
        Target(python_version="3.10", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.18.0", max="1.25.0"),
            VersionRange(min="1.25.2", max=None),
        ],
        Target(python_version="3.11", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="0.0.1", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.14.29"),
            VersionRange(min="0.14.31", max=None),
        ],
        Target(python_version="3.11", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="0.13.4", max="0.13.18"),
            VersionRange(min="0.13.25", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.13.55"),
            VersionRange(min="0.13.57", max="0.14.10"),
            VersionRange(min="0.14.12", max="0.14.29"),
            VersionRange(min="0.14.31", max="0.17.2"),
            VersionRange(min="0.17.5", max=None),
        ],
        Target(python_version="3.11", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.11", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="0.12.21", max="0.12.21"),
            VersionRange(min="0.12.23", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.11", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.19.3"),
            VersionRange(min="0.19.5", max=None),
        ],
        Target(python_version="3.11", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.18.0", max="1.25.0"),
            VersionRange(min="1.25.2", max=None),
        ],
        Target(python_version="3.12", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="0.0.1", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.14.29"),
            VersionRange(min="0.14.31", max=None),
        ],
        Target(python_version="3.12", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="0.13.4", max="0.13.18"),
            VersionRange(min="0.13.25", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.13.55"),
            VersionRange(min="0.13.57", max="0.14.10"),
            VersionRange(min="0.14.12", max="0.14.29"),
            VersionRange(min="0.14.31", max="0.17.2"),
            VersionRange(min="0.17.5", max=None),
        ],
        Target(python_version="3.12", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.12", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="0.12.21", max="0.12.21"),
            VersionRange(min="0.12.23", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.12", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.19.3"),
            VersionRange(min="0.19.5", max=None),
        ],
        Target(python_version="3.12", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.18.0", max="1.25.0"),
            VersionRange(min="1.25.2", max=None),
        ],
        Target(python_version="3.13", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="0.0.1", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.14.29"),
            VersionRange(min="0.14.31", max=None),
        ],
        Target(python_version="3.13", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="0.13.4", max="0.13.18"),
            VersionRange(min="0.13.25", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.13.55"),
            VersionRange(min="0.13.57", max="0.14.10"),
            VersionRange(min="0.14.12", max="0.14.29"),
            VersionRange(min="0.14.31", max="0.17.2"),
            VersionRange(min="0.17.5", max=None),
        ],
        Target(python_version="3.13", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.13", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="0.12.21", max="0.12.21"),
            VersionRange(min="0.12.23", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.13", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.19.3"),
            VersionRange(min="0.19.5", max=None),
        ],
        Target(python_version="3.13", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.18.0", max="1.25.0"),
            VersionRange(min="1.25.2", max=None),
        ],
        Target(python_version="3.13", free_threaded=True, os="linux", arch="x86_64"): [],
        Target(python_version="3.13", free_threaded=True, os="linux", arch="arm64"): [],
        Target(python_version="3.13", free_threaded=True, os="macos", arch="x86_64"): [],
        Target(python_version="3.13", free_threaded=True, os="macos", arch="arm64"): [],
        Target(python_version="3.13", free_threaded=True, os="windows", arch="x86_64"): [],
        Target(python_version="3.13", free_threaded=True, os="windows", arch="arm64"): [],
        Target(python_version="3.14", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="0.0.1", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.14.29"),
            VersionRange(min="0.14.31", max=None),
        ],
        Target(python_version="3.14", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="0.13.4", max="0.13.18"),
            VersionRange(min="0.13.25", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.13.55"),
            VersionRange(min="0.13.57", max="0.14.10"),
            VersionRange(min="0.14.12", max="0.14.29"),
            VersionRange(min="0.14.31", max="0.17.2"),
            VersionRange(min="0.17.5", max=None),
        ],
        Target(python_version="3.14", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.14", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="0.12.21", max="0.12.21"),
            VersionRange(min="0.12.23", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.14", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.19.3"),
            VersionRange(min="0.19.5", max=None),
        ],
        Target(python_version="3.14", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.18.0", max="1.25.0"),
            VersionRange(min="1.25.2", max=None),
        ],
        Target(python_version="3.14", free_threaded=True, os="linux", arch="x86_64"): [],
        Target(python_version="3.14", free_threaded=True, os="linux", arch="arm64"): [],
        Target(python_version="3.14", free_threaded=True, os="macos", arch="x86_64"): [],
        Target(python_version="3.14", free_threaded=True, os="macos", arch="arm64"): [],
        Target(python_version="3.14", free_threaded=True, os="windows", arch="x86_64"): [],
        Target(python_version="3.14", free_threaded=True, os="windows", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="0.0.1", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.14.29"),
            VersionRange(min="0.14.31", max=None),
        ],
        Target(python_version="3.15", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="0.13.4", max="0.13.18"),
            VersionRange(min="0.13.25", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.13.55"),
            VersionRange(min="0.13.57", max="0.14.10"),
            VersionRange(min="0.14.12", max="0.14.29"),
            VersionRange(min="0.14.31", max="0.17.2"),
            VersionRange(min="0.17.5", max=None),
        ],
        Target(python_version="3.15", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.15", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="0.12.21", max="0.12.21"),
            VersionRange(min="0.12.23", max="0.13.29"),
            VersionRange(min="0.13.31", max=None),
        ],
        Target(python_version="3.15", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="0.7.3", max="0.13.29"),
            VersionRange(min="0.13.31", max="0.19.3"),
            VersionRange(min="0.19.5", max=None),
        ],
        Target(python_version="3.15", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.18.0", max="1.25.0"),
            VersionRange(min="1.25.2", max=None),
        ],
        Target(python_version="3.15", free_threaded=True, os="linux", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="linux", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="macos", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="macos", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="windows", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="windows", arch="arm64"): [],
    }
