r"""Automatically discovered compatibility constraints for
``pyarrow``.

Generated by ``debug/generate_discovered_compat.py``. Do not edit by
hand: re-run the script to refresh this module.
"""

from __future__ import annotations

__all__ = ["PKG_NAME", "compat"]

from feu.compat.registry import VersionRange
from feu.compat.target import Target

PKG_NAME = "pyarrow"


def compat() -> dict[Target, list[VersionRange]]:
    r"""Return the precomputed compatibility constraints for
    ``pyarrow``."""
    return {
        Target(python_version="3.9", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="3.0.0", max="21.0.0")
        ],
        Target(python_version="3.9", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="4.0.0", max="21.0.0")
        ],
        Target(python_version="3.9", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="3.0.0", max="21.0.0")
        ],
        Target(python_version="3.9", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="5.0.0", max="21.0.0")
        ],
        Target(python_version="3.9", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="3.0.0", max="21.0.0")
        ],
        Target(python_version="3.9", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.10", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="6.0.0", max=None)
        ],
        Target(python_version="3.10", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="6.0.0", max=None)
        ],
        Target(python_version="3.10", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="6.0.0", max=None)
        ],
        Target(python_version="3.10", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="6.0.0", max=None)
        ],
        Target(python_version="3.10", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="6.0.0", max=None)
        ],
        Target(python_version="3.10", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.11", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="10.0.1", max=None)
        ],
        Target(python_version="3.11", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="10.0.1", max=None)
        ],
        Target(python_version="3.11", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="10.0.1", max=None)
        ],
        Target(python_version="3.11", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="10.0.1", max=None)
        ],
        Target(python_version="3.11", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="10.0.1", max=None)
        ],
        Target(python_version="3.11", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.12", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="14.0.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="14.0.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="14.0.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="14.0.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="14.0.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.13", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="18.0.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="18.0.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="18.0.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="18.0.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="18.0.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.13", free_threaded=True, os="linux", arch="x86_64"): [
            VersionRange(min="18.0.0", max="24.0.0")
        ],
        Target(python_version="3.13", free_threaded=True, os="linux", arch="arm64"): [
            VersionRange(min="18.0.0", max="24.0.0")
        ],
        Target(python_version="3.13", free_threaded=True, os="macos", arch="x86_64"): [
            VersionRange(min="18.0.0", max="24.0.0")
        ],
        Target(python_version="3.13", free_threaded=True, os="macos", arch="arm64"): [
            VersionRange(min="18.0.0", max="24.0.0")
        ],
        Target(python_version="3.13", free_threaded=True, os="windows", arch="x86_64"): [
            VersionRange(min="20.0.0", max="24.0.0")
        ],
        Target(python_version="3.13", free_threaded=True, os="windows", arch="arm64"): [],
        Target(python_version="3.14", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="22.0.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="22.0.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="22.0.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="22.0.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="22.0.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.14", free_threaded=True, os="linux", arch="x86_64"): [
            VersionRange(min="22.0.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="linux", arch="arm64"): [
            VersionRange(min="22.0.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="macos", arch="x86_64"): [
            VersionRange(min="22.0.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="macos", arch="arm64"): [
            VersionRange(min="22.0.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="windows", arch="x86_64"): [
            VersionRange(min="22.0.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="windows", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=False, os="linux", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=False, os="linux", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=False, os="macos", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=False, os="macos", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=False, os="windows", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="linux", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="linux", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="macos", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="macos", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="windows", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="windows", arch="arm64"): [],
    }
