r"""Automatically discovered compatibility constraints for
``scikit-learn``.

Generated by ``debug/generate_discovered_compat.py``. Do not edit by
hand: re-run the script to refresh this module.
"""

from __future__ import annotations

__all__ = ["PKG_NAME", "compat"]

from feu.compat.registry import VersionRange
from feu.compat.target import Target

PKG_NAME = "scikit-learn"


def compat() -> dict[Target, list[VersionRange]]:
    r"""Return the precomputed compatibility constraints for
    ``scikit-learn``."""
    return {
        Target(python_version="3.9", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="0.24.0", max="1.6.1")
        ],
        Target(python_version="3.9", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="0.24.0", max="1.6.1")
        ],
        Target(python_version="3.9", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="0.24.0", max="1.6.1")
        ],
        Target(python_version="3.9", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.0.2", max="1.6.1")
        ],
        Target(python_version="3.9", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="0.24.0", max="1.6.1")
        ],
        Target(python_version="3.9", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.10", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.0.2", max="1.7.2")
        ],
        Target(python_version="3.10", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.0.2", max="1.7.2")
        ],
        Target(python_version="3.10", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.0.2", max="1.7.2")
        ],
        Target(python_version="3.10", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.0.2", max="1.7.2")
        ],
        Target(python_version="3.10", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.0.2", max="1.7.2")
        ],
        Target(python_version="3.10", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.11", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.1.3", max=None)
        ],
        Target(python_version="3.11", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.1.3", max=None)
        ],
        Target(python_version="3.11", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.1.3", max=None)
        ],
        Target(python_version="3.11", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.1.3", max=None)
        ],
        Target(python_version="3.11", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.1.3", max=None)
        ],
        Target(python_version="3.11", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.8.0", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.3.1", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.3.1", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.3.1", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.3.1", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.3.1", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.8.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.5.2", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.5.2", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.5.2", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.5.2", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.5.2", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.8.0", max=None)
        ],
        Target(python_version="3.13", free_threaded=True, os="linux", arch="x86_64"): [
            VersionRange(min="1.6.0", max="1.8.0")
        ],
        Target(python_version="3.13", free_threaded=True, os="linux", arch="arm64"): [
            VersionRange(min="1.7.1", max="1.8.0")
        ],
        Target(python_version="3.13", free_threaded=True, os="macos", arch="x86_64"): [
            VersionRange(min="1.6.0", max="1.8.0")
        ],
        Target(python_version="3.13", free_threaded=True, os="macos", arch="arm64"): [
            VersionRange(min="1.6.0", max="1.8.0")
        ],
        Target(python_version="3.13", free_threaded=True, os="windows", arch="x86_64"): [
            VersionRange(min="1.6.0", max="1.8.0")
        ],
        Target(python_version="3.13", free_threaded=True, os="windows", arch="arm64"): [
            VersionRange(min="1.8.0", max="1.8.0")
        ],
        Target(python_version="3.14", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.7.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.7.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.7.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.7.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.7.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.8.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="linux", arch="x86_64"): [
            VersionRange(min="1.8.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="linux", arch="arm64"): [
            VersionRange(min="1.8.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="macos", arch="x86_64"): [
            VersionRange(min="1.8.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="macos", arch="arm64"): [
            VersionRange(min="1.8.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="windows", arch="x86_64"): [
            VersionRange(min="1.8.0", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="windows", arch="arm64"): [
            VersionRange(min="1.8.0", max=None)
        ],
        Target(python_version="3.15", free_threaded=False, os="linux", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=False, os="linux", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=False, os="macos", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=False, os="macos", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=False, os="windows", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="linux", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="linux", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="macos", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="macos", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="windows", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="windows", arch="arm64"): [],
    }
