r"""Automatically discovered compatibility constraints for
``scipy``.

Generated by ``debug/generate_discovered_compat.py``. Do not edit by
hand: re-run the script to refresh this module.
"""

from __future__ import annotations

__all__ = ["PKG_NAME", "compat"]

from feu.compat.registry import VersionRange
from feu.compat.target import Target

PKG_NAME = "scipy"


def compat() -> dict[Target, list[VersionRange]]:
    r"""Return the precomputed compatibility constraints for
    ``scipy``."""
    return {
        Target(python_version="3.9", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.5.4", max="1.13.1")
        ],
        Target(python_version="3.9", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.5.4", max="1.13.1")
        ],
        Target(python_version="3.9", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.5.4", max="1.13.1")
        ],
        Target(python_version="3.9", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.7.3", max="1.13.1")
        ],
        Target(python_version="3.9", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.5.4", max="1.13.1")
        ],
        Target(python_version="3.9", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.10", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.7.2", max="1.15.3")
        ],
        Target(python_version="3.10", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.7.2", max="1.15.3")
        ],
        Target(python_version="3.10", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.7.2", max="1.15.3")
        ],
        Target(python_version="3.10", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.7.3", max="1.15.3")
        ],
        Target(python_version="3.10", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.7.2", max="1.15.3")
        ],
        Target(python_version="3.10", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.11", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.9.2", max="1.17.1")
        ],
        Target(python_version="3.11", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.9.2", max="1.17.1")
        ],
        Target(python_version="3.11", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.9.2", max="1.17.1")
        ],
        Target(python_version="3.11", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.9.2", max="1.17.1")
        ],
        Target(python_version="3.11", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.9.2", max="1.17.1")
        ],
        Target(python_version="3.11", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.16.2", max="1.17.1")
        ],
        Target(python_version="3.12", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.11.2", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.11.2", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.11.2", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.11.2", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.11.2", max=None)
        ],
        Target(python_version="3.12", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.16.2", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.14.1", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.14.1", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.14.1", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.14.1", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.14.1", max=None)
        ],
        Target(python_version="3.13", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.16.2", max=None)
        ],
        Target(python_version="3.13", free_threaded=True, os="linux", arch="x86_64"): [
            VersionRange(min="1.15.0", max="1.17.1")
        ],
        Target(python_version="3.13", free_threaded=True, os="linux", arch="arm64"): [
            VersionRange(min="1.15.2", max="1.17.1")
        ],
        Target(python_version="3.13", free_threaded=True, os="macos", arch="x86_64"): [
            VersionRange(min="1.15.0", max="1.17.1")
        ],
        Target(python_version="3.13", free_threaded=True, os="macos", arch="arm64"): [
            VersionRange(min="1.15.0", max="1.17.1")
        ],
        Target(python_version="3.13", free_threaded=True, os="windows", arch="x86_64"): [
            VersionRange(min="1.15.0", max="1.17.1")
        ],
        Target(python_version="3.13", free_threaded=True, os="windows", arch="arm64"): [
            VersionRange(min="1.16.2", max="1.17.1")
        ],
        Target(python_version="3.14", free_threaded=False, os="linux", arch="x86_64"): [
            VersionRange(min="1.16.1", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="linux", arch="arm64"): [
            VersionRange(min="1.16.1", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="macos", arch="x86_64"): [
            VersionRange(min="1.16.1", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="macos", arch="arm64"): [
            VersionRange(min="1.16.1", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="windows", arch="x86_64"): [
            VersionRange(min="1.16.1", max=None)
        ],
        Target(python_version="3.14", free_threaded=False, os="windows", arch="arm64"): [
            VersionRange(min="1.16.2", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="linux", arch="x86_64"): [
            VersionRange(min="1.16.1", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="linux", arch="arm64"): [
            VersionRange(min="1.16.1", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="macos", arch="x86_64"): [
            VersionRange(min="1.16.1", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="macos", arch="arm64"): [
            VersionRange(min="1.16.1", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="windows", arch="x86_64"): [
            VersionRange(min="1.16.1", max=None)
        ],
        Target(python_version="3.14", free_threaded=True, os="windows", arch="arm64"): [
            VersionRange(min="1.16.2", max=None)
        ],
        Target(python_version="3.15", free_threaded=False, os="linux", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=False, os="linux", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=False, os="macos", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=False, os="macos", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=False, os="windows", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=False, os="windows", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="linux", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="linux", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="macos", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="macos", arch="arm64"): [],
        Target(python_version="3.15", free_threaded=True, os="windows", arch="x86_64"): [],
        Target(python_version="3.15", free_threaded=True, os="windows", arch="arm64"): [],
    }
