name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  cyclic-import:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup python environment
        uses: durandtibo/setup-venv-uv-action@v0.1.0

      - name: check feu
        run: |
          python -c "import feu"

      - name: check feu.install
        run: |
          python -c "from feu import install"
          python -c "from feu.install import pip"

      - name: check feu.github
        run: |
          python -c "from feu import github"

      - name: check feu.utils
        run: |
          python -c "from feu import utils"

      - name: check feu.version
        run: |
          python -c "from feu import version"
