name: Debug
on:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  debug:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.14', '3.13', '3.12', '3.11', '3.10' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          pip install "feu[all]"

      - name: Run some checks
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          python tests/package_checks.py
