name: Update Discovered Compatibility

on:
  schedule:
    - cron: "0 6 * * 5" # run every Friday at 6:00 AM UTC
  workflow_call:
  workflow_dispatch: # to trigger manually

permissions:
  contents: write
  pull-requests: write

jobs:
  update-discovered-compat:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup python environment
        uses: durandtibo/setup-venv-uv-action@v0.1.0

      - name: Discover package compatibility
        run: |
          python dev/generate_discovered_compat.py

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

      - uses: peter-evans/create-pull-request@v8
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/discovered-compat
          title: Update discovered compatibility constraints
          commit-message: "Update discovered compatibility constraints"
          body: Update automatically discovered package/Python-version compatibility constraints.
          author: ci-bot <${{secrets.CI_BOT_EMAIL}}>
