name: Verify Compatibity
on:
  schedule:
    - cron: "0 6 * * 3" # run every Wednesday at 6:00 AM UTC
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  all:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [
          ubuntu-24.04,
          ubuntu-24.04-arm,
          macos-26,
          macos-15-intel,
        ]
        python-version: [ '3.14', '3.14t', '3.13', '3.13t', '3.12', '3.11', '3.10' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup python environment
        uses: durandtibo/setup-venv-uv-action@v0.0.5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install all compatible package versions
        run: |
          python dev/install_all_versions.py --installer uv
